### ISSUE TITLE
The result of point cloud completion cannot be submitted to Codalab

### ISSUE THREAD

**Issue by MingyeXu** [paul007pl/MVP_Benchmark#13]
Recently, we were unable to submit results with an error of “Sorry, filed to upload file.” 
Is there something wrong with the codalab?

**Comment by paul007pl** [comment]
Hi, Mingye,
We checked our website, and failed to find any issues.
Hence, we think it should be a system issue, and we found this:
https://github.com/codalab/codalab-competitions/issues/2983

Maybe we wait for the codalab team first.
Once it works, we will support and then increase the daily submisstion limit.

**Comment by MingyeXu** [comment]
Thanks for your reply!

**Comment by conjuringjha** [comment]
It's been more than an hour since I uploaded the submission file, but the upload hasn't completed till yet.  This is my  first submission so I'm not sure how long it generally takes for the upload to complete, besides my internet connection is good enough to make any upload that size in the passed amount of time. Is there some submission issue ongoing or is the problem on my end?

**Comment by zhulf0804** [comment]
The same problem "Sorry, filed to upload file." happened to me now.

**Comment by MingyeXu** [comment]
The Codalab now works normally.
